# Generated by Django 5.0.7 on 2024-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_set_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='relation',
            field=models.ManyToManyField(to='api.question'),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
