# Generated by Django 4.1 on 2024-07-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_task_question_methods_test_suite"),
    ]

    operations = [
        migrations.RemoveField(model_name="suite", name="test_id",),
        migrations.RemoveField(model_name="test", name="task_id",),
        migrations.AddField(
            model_name="task",
            name="test_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.test"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="suite_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.suite"
            ),
        ),
    ]
