# Generated by Django 5.0.7 on 2024-07-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_test_id_task_test_rename_suite_id_test_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='cate',
            field=models.CharField(default='越狱攻击', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='behavior',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
