# Generated by Django 5.0.7 on 2024-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_set_cate_alter_question_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='cate',
            field=models.CharField(default='jailbreak', max_length=50),
        ),
    ]
